FROM liferay/portal:7.2.0-ga1
MAINTAINER Antonio Musarra <antonio.musarra@gmail.com>

COPY --chown=liferay:liferay liferay/configs/portal-ext.properties $LIFERAY_HOME/
COPY --chown=liferay:liferay liferay/osgi/configs/* $LIFERAY_HOME/osgi/configs/

USER root

RUN mkdir -p /data/liferay/document_library \
  && chown -R liferay:liferay /data

USER liferay