FROM liferay/portal:7.2.1-ga2
MAINTAINER Antonio Musarra <antonio.musarra@gmail.com>

ADD --chown=liferay:liferay https://raw.githubusercontent.com/lgdd/wait-for-liferay/master/wait-for-liferay.sh /usr/local/bin/
RUN chmod a+x /usr/local/bin/wait-for-liferay.sh

COPY --chown=liferay:liferay liferay/configs/portal-ext.properties $LIFERAY_HOME/
COPY --chown=liferay:liferay liferay/osgi/configs/* $LIFERAY_HOME/osgi/configs/

USER root

RUN mkdir -p /data/liferay/document_library \
  && chown -R liferay:liferay /data

USER liferay
